"""Versioned bilingual programming knowledge-point registry.

Entries are curated concepts rather than generated aliases.  Stable ids are
sent to the API; localized labels are display-only and never change prompts by
accident.
"""

from __future__ import annotations

KNOWLEDGE_VERSION = "programming-knowledge-2026-09.v1"

_CATEGORIES = (
    ("language", "语言基础", "Language fundamentals"),
    ("programming", "程序设计", "Programming foundations"),
    ("linear-structures", "线性数据结构", "Linear data structures"),
    ("sorting-searching", "排序与查找", "Sorting and searching"),
    ("strings", "字符串", "Strings"),
    ("trees", "树结构", "Trees"),
    ("graphs", "图论", "Graph theory"),
    ("dynamic-programming", "动态规划", "Dynamic programming"),
    ("search-greedy", "搜索与贪心", "Search and greedy algorithms"),
    ("mathematics", "数学与数论", "Mathematics and number theory"),
    ("geometry", "计算几何", "Computational geometry"),
    ("advanced-structures", "高级数据结构", "Advanced data structures"),
    ("complexity-engineering", "复杂度与工程", "Complexity and engineering"),
)

KNOWLEDGE_CATEGORIES = tuple(
    {"id": category_id, "zh-CN": zh, "en": en} for category_id, zh, en in _CATEGORIES
)

_ENTRIES = (
    # Language fundamentals
    ("language.variables", "language", "变量与赋值", "Variables and assignment"),
    ("language.numeric-types", "language", "整数与浮点数", "Integers and floating point"),
    ("language.booleans", "language", "布尔值与逻辑运算", "Booleans and logic"),
    ("language.expressions", "language", "表达式与运算符", "Expressions and operators"),
    ("language.precedence", "language", "运算符优先级", "Operator precedence"),
    ("language.conditionals", "language", "条件分支", "Conditional branches"),
    ("language.for-loops", "language", "for 循环", "For loops"),
    ("language.while-loops", "language", "while 循环", "While loops"),
    ("language.loop-control", "language", "循环控制", "Loop control"),
    ("language.functions", "language", "函数定义与调用", "Functions"),
    ("language.parameters", "language", "参数与返回值", "Parameters and return values"),
    ("language.scope", "language", "变量作用域", "Variable scope"),
    ("language.recursion", "language", "递归基础", "Recursion fundamentals"),
    ("language.input-output", "language", "标准输入输出", "Standard input and output"),
    ("language.formatting", "language", "格式化输出", "Formatted output"),
    ("language.exceptions", "language", "异常处理", "Exception handling"),
    ("language.modules", "language", "模块与导入", "Modules and imports"),
    ("language.comprehensions", "language", "推导式", "Comprehensions"),
    ("language.iterators", "language", "迭代器", "Iterators"),
    ("language.generators", "language", "生成器", "Generators"),
    ("language.lambdas", "language", "匿名函数", "Lambda functions"),
    ("language.classes", "language", "类与对象", "Classes and objects"),
    ("language.inheritance", "language", "继承与多态", "Inheritance and polymorphism"),
    ("language.dataclasses", "language", "数据类", "Data classes"),
    # Programming foundations
    ("programming.decomposition", "programming", "问题分解", "Problem decomposition"),
    ("programming.invariants", "programming", "循环不变量", "Loop invariants"),
    ("programming.simulation", "programming", "过程模拟", "Process simulation"),
    ("programming.enumeration", "programming", "枚举", "Enumeration"),
    ("programming.prefix-sum", "programming", "一维前缀和", "One-dimensional prefix sums"),
    ("programming.prefix-sum-2d", "programming", "二维前缀和", "Two-dimensional prefix sums"),
    ("programming.difference-array", "programming", "差分数组", "Difference arrays"),
    ("programming.two-pointers", "programming", "双指针", "Two pointers"),
    ("programming.sliding-window", "programming", "滑动窗口", "Sliding window"),
    ("programming.coordinate-compression", "programming", "离散化", "Coordinate compression"),
    ("programming.offline-processing", "programming", "离线处理", "Offline processing"),
    ("programming.state-machine", "programming", "状态机", "State machines"),
    ("programming.bitmask", "programming", "位掩码", "Bitmasks"),
    ("programming.subset-enumeration", "programming", "子集枚举", "Subset enumeration"),
    ("programming.meet-in-middle", "programming", "折半枚举", "Meet in the middle"),
    ("programming.randomized", "programming", "随机化算法", "Randomized algorithms"),
    ("programming.constructive", "programming", "构造算法", "Constructive algorithms"),
    ("programming.interactive-model", "programming", "交互模型基础", "Interactive problem models"),
    ("programming.streaming", "programming", "流式数据处理", "Streaming data processing"),
    ("programming.event-sweep", "programming", "事件扫描", "Event sweeps"),
    # Linear data structures
    ("linear.array", "linear-structures", "数组", "Arrays"),
    ("linear.matrix", "linear-structures", "矩阵", "Matrices"),
    ("linear.dynamic-array", "linear-structures", "动态数组", "Dynamic arrays"),
    ("linear.linked-list", "linear-structures", "单向链表", "Singly linked lists"),
    ("linear.doubly-linked-list", "linear-structures", "双向链表", "Doubly linked lists"),
    ("linear.stack", "linear-structures", "栈", "Stacks"),
    ("linear.queue", "linear-structures", "队列", "Queues"),
    ("linear.deque", "linear-structures", "双端队列", "Deques"),
    ("linear.priority-queue", "linear-structures", "优先队列", "Priority queues"),
    ("linear.heap", "linear-structures", "二叉堆", "Binary heaps"),
    ("linear.hash-table", "linear-structures", "哈希表", "Hash tables"),
    ("linear.hash-set", "linear-structures", "哈希集合", "Hash sets"),
    ("linear.ordered-map", "linear-structures", "有序映射", "Ordered maps"),
    ("linear.sparse-table", "linear-structures", "稀疏表", "Sparse tables"),
    ("linear.monotonic-stack", "linear-structures", "单调栈", "Monotonic stacks"),
    ("linear.monotonic-queue", "linear-structures", "单调队列", "Monotonic queues"),
    ("linear.circular-buffer", "linear-structures", "循环缓冲区", "Circular buffers"),
    ("linear.bitmap", "linear-structures", "位图", "Bitmaps"),
    # Sorting and searching
    ("sort.bubble", "sorting-searching", "冒泡排序", "Bubble sort"),
    ("sort.selection", "sorting-searching", "选择排序", "Selection sort"),
    ("sort.insertion", "sorting-searching", "插入排序", "Insertion sort"),
    ("sort.merge", "sorting-searching", "归并排序", "Merge sort"),
    ("sort.quick", "sorting-searching", "快速排序", "Quicksort"),
    ("sort.heap", "sorting-searching", "堆排序", "Heap sort"),
    ("sort.counting", "sorting-searching", "计数排序", "Counting sort"),
    ("sort.radix", "sorting-searching", "基数排序", "Radix sort"),
    ("sort.bucket", "sorting-searching", "桶排序", "Bucket sort"),
    ("sort.stability", "sorting-searching", "排序稳定性", "Sorting stability"),
    ("sort.custom-order", "sorting-searching", "自定义排序规则", "Custom ordering"),
    ("search.linear", "sorting-searching", "顺序查找", "Linear search"),
    ("search.binary", "sorting-searching", "二分查找", "Binary search"),
    ("search.answer", "sorting-searching", "二分答案", "Binary search on answer"),
    ("search.ternary", "sorting-searching", "三分搜索", "Ternary search"),
    ("search.quickselect", "sorting-searching", "快速选择", "Quickselect"),
    ("search.order-statistic", "sorting-searching", "顺序统计量", "Order statistics"),
    ("search.lower-upper-bound", "sorting-searching", "上下界查找", "Lower and upper bounds"),
    # Strings
    ("string.basics", "strings", "字符串基础", "String fundamentals"),
    ("string.parsing", "strings", "文本解析", "Text parsing"),
    ("string.tokenization", "strings", "词法切分", "Tokenization"),
    ("string.frequency", "strings", "字符频次统计", "Character frequencies"),
    ("string.palindrome", "strings", "回文", "Palindromes"),
    ("string.parentheses", "strings", "括号匹配", "Bracket matching"),
    ("string.trie", "strings", "字典树", "Tries"),
    ("string.kmp", "strings", "KMP 字符串匹配", "KMP matching"),
    ("string.z-function", "strings", "Z 函数", "Z function"),
    ("string.rolling-hash", "strings", "字符串哈希", "Rolling hashes"),
    ("string.rabin-karp", "strings", "Rabin–Karp 算法", "Rabin–Karp algorithm"),
    ("string.aho-corasick", "strings", "AC 自动机", "Aho–Corasick automaton"),
    ("string.manacher", "strings", "Manacher 算法", "Manacher algorithm"),
    ("string.suffix-array", "strings", "后缀数组", "Suffix arrays"),
    ("string.suffix-automaton", "strings", "后缀自动机", "Suffix automata"),
    ("string.edit-distance", "strings", "编辑距离", "Edit distance"),
    ("string.lcs", "strings", "最长公共子序列", "Longest common subsequence"),
    ("string.regex", "strings", "正则表达式", "Regular expressions"),
    # Trees
    ("tree.binary", "trees", "二叉树", "Binary trees"),
    ("tree.traversal", "trees", "树的遍历", "Tree traversal"),
    ("tree.bst", "trees", "二叉搜索树", "Binary search trees"),
    ("tree.reconstruction", "trees", "树的重建", "Tree reconstruction"),
    ("tree.diameter", "trees", "树的直径", "Tree diameter"),
    ("tree.centroid", "trees", "树的重心", "Tree centroids"),
    ("tree.lca", "trees", "最近公共祖先", "Lowest common ancestor"),
    ("tree.binary-lifting", "trees", "倍增", "Binary lifting"),
    ("tree.euler-tour", "trees", "欧拉序", "Euler tours"),
    ("tree.subtree", "trees", "子树统计", "Subtree aggregation"),
    ("tree.rerooting", "trees", "换根算法", "Rerooting"),
    ("tree.dp", "trees", "树形动态规划", "Tree dynamic programming"),
    ("tree.heavy-light", "trees", "重链剖分", "Heavy-light decomposition"),
    ("tree.centroid-decomposition", "trees", "点分治", "Centroid decomposition"),
    ("tree.virtual-tree", "trees", "虚树", "Virtual trees"),
    ("tree.cartesian", "trees", "笛卡尔树", "Cartesian trees"),
    ("tree.huffman", "trees", "哈夫曼树", "Huffman trees"),
    ("tree.expression", "trees", "表达式树", "Expression trees"),
    # Graph theory
    ("graph.representation", "graphs", "图的存储", "Graph representations"),
    ("graph.dfs", "graphs", "图上深度优先搜索", "Graph depth-first search"),
    ("graph.bfs", "graphs", "图上广度优先搜索", "Graph breadth-first search"),
    ("graph.connected-components", "graphs", "连通分量", "Connected components"),
    ("graph.flood-fill", "graphs", "洪水填充", "Flood fill"),
    ("graph.topological-sort", "graphs", "拓扑排序", "Topological sorting"),
    ("graph.cycle-directed", "graphs", "有向图环检测", "Directed cycle detection"),
    ("graph.cycle-undirected", "graphs", "无向图环检测", "Undirected cycle detection"),
    ("graph.bipartite", "graphs", "二分图判定", "Bipartite graph testing"),
    ("graph.scc", "graphs", "强连通分量", "Strongly connected components"),
    ("graph.bridges", "graphs", "桥", "Bridges"),
    ("graph.articulation", "graphs", "割点", "Articulation points"),
    ("graph.eulerian", "graphs", "欧拉路径", "Eulerian paths"),
    ("graph.hamiltonian", "graphs", "哈密顿路径", "Hamiltonian paths"),
    ("graph.shortest-unweighted", "graphs", "无权最短路", "Unweighted shortest paths"),
    ("graph.dijkstra", "graphs", "Dijkstra 最短路", "Dijkstra shortest paths"),
    ("graph.bellman-ford", "graphs", "Bellman–Ford 算法", "Bellman–Ford algorithm"),
    ("graph.floyd-warshall", "graphs", "Floyd–Warshall 算法", "Floyd–Warshall algorithm"),
    ("graph.dag-shortest", "graphs", "DAG 最短路", "DAG shortest paths"),
    ("graph.zero-one-bfs", "graphs", "0-1 BFS", "0-1 BFS"),
    ("graph.mst", "graphs", "最小生成树", "Minimum spanning trees"),
    ("graph.kruskal", "graphs", "Kruskal 算法", "Kruskal algorithm"),
    ("graph.prim", "graphs", "Prim 算法", "Prim algorithm"),
    ("graph.max-flow", "graphs", "最大流", "Maximum flow"),
    ("graph.min-cut", "graphs", "最小割", "Minimum cut"),
    ("graph.bipartite-matching", "graphs", "二分图匹配", "Bipartite matching"),
    ("graph.min-cost-flow", "graphs", "最小费用流", "Minimum-cost flow"),
    ("graph.difference-constraints", "graphs", "差分约束", "Difference constraints"),
    # Dynamic programming
    ("dp.state-design", "dynamic-programming", "状态设计", "DP state design"),
    ("dp.transition", "dynamic-programming", "状态转移", "DP transitions"),
    ("dp.memoization", "dynamic-programming", "记忆化搜索", "Memoization"),
    ("dp.linear", "dynamic-programming", "线性动态规划", "Linear dynamic programming"),
    ("dp.grid", "dynamic-programming", "网格动态规划", "Grid dynamic programming"),
    ("dp.interval", "dynamic-programming", "区间动态规划", "Interval dynamic programming"),
    ("dp.sequence", "dynamic-programming", "序列动态规划", "Sequence dynamic programming"),
    ("dp.lis", "dynamic-programming", "最长递增子序列", "Longest increasing subsequence"),
    ("dp.knapsack-01", "dynamic-programming", "0-1 背包", "0-1 knapsack"),
    ("dp.knapsack-complete", "dynamic-programming", "完全背包", "Unbounded knapsack"),
    ("dp.knapsack-multiple", "dynamic-programming", "多重背包", "Bounded knapsack"),
    ("dp.subset-sum", "dynamic-programming", "子集和", "Subset sum"),
    ("dp.bitmask", "dynamic-programming", "状压动态规划", "Bitmask dynamic programming"),
    ("dp.digit", "dynamic-programming", "数位动态规划", "Digit dynamic programming"),
    ("dp.probability", "dynamic-programming", "概率动态规划", "Probability dynamic programming"),
    ("dp.expectation", "dynamic-programming", "期望动态规划", "Expectation dynamic programming"),
    ("dp.game", "dynamic-programming", "博弈动态规划", "Game dynamic programming"),
    ("dp.profile", "dynamic-programming", "轮廓线动态规划", "Profile dynamic programming"),
    (
        "dp.optimization-monotone",
        "dynamic-programming",
        "单调队列优化 DP",
        "Monotone-queue DP optimization",
    ),
    ("dp.optimization-convex", "dynamic-programming", "斜率优化 DP", "Convex-hull DP optimization"),
    # Search and greedy
    ("search.dfs", "search-greedy", "深度优先搜索", "Depth-first search"),
    ("search.bfs", "search-greedy", "广度优先搜索", "Breadth-first search"),
    ("search.backtracking", "search-greedy", "回溯", "Backtracking"),
    ("search.pruning", "search-greedy", "搜索剪枝", "Search pruning"),
    ("search.iterative-deepening", "search-greedy", "迭代加深", "Iterative deepening"),
    ("search.bidirectional", "search-greedy", "双向搜索", "Bidirectional search"),
    ("search.a-star", "search-greedy", "A* 搜索", "A* search"),
    ("search.branch-bound", "search-greedy", "分支限界", "Branch and bound"),
    ("greedy.exchange", "search-greedy", "贪心交换论证", "Greedy exchange arguments"),
    ("greedy.interval", "search-greedy", "区间贪心", "Interval greedy algorithms"),
    ("greedy.scheduling", "search-greedy", "任务调度贪心", "Greedy scheduling"),
    ("greedy.covering", "search-greedy", "覆盖问题贪心", "Greedy covering"),
    ("greedy.merging", "search-greedy", "合并代价贪心", "Greedy merging"),
    ("greedy.priority", "search-greedy", "优先队列贪心", "Priority-queue greedy algorithms"),
    ("greedy.matroid", "search-greedy", "拟阵贪心", "Matroid greedy algorithms"),
    # Mathematics and number theory
    ("math.gcd", "mathematics", "最大公约数", "Greatest common divisor"),
    ("math.lcm", "mathematics", "最小公倍数", "Least common multiple"),
    ("math.euclidean", "mathematics", "欧几里得算法", "Euclidean algorithm"),
    ("math.extended-gcd", "mathematics", "扩展欧几里得算法", "Extended Euclidean algorithm"),
    ("math.primes", "mathematics", "素数判定", "Primality testing"),
    ("math.sieve", "mathematics", "埃氏筛", "Sieve of Eratosthenes"),
    ("math.linear-sieve", "mathematics", "线性筛", "Linear sieve"),
    ("math.factorization", "mathematics", "整数分解", "Integer factorization"),
    ("math.modular", "mathematics", "模运算", "Modular arithmetic"),
    ("math.fast-power", "mathematics", "快速幂", "Binary exponentiation"),
    ("math.modular-inverse", "mathematics", "模逆元", "Modular inverses"),
    ("math.crt", "mathematics", "中国剩余定理", "Chinese remainder theorem"),
    ("math.diophantine", "mathematics", "丢番图方程", "Diophantine equations"),
    ("math.combinatorics", "mathematics", "组合数学", "Combinatorics"),
    ("math.permutations", "mathematics", "排列计数", "Permutation counting"),
    ("math.binomial", "mathematics", "二项式系数", "Binomial coefficients"),
    ("math.inclusion-exclusion", "mathematics", "容斥原理", "Inclusion–exclusion"),
    ("math.pigeonhole", "mathematics", "抽屉原理", "Pigeonhole principle"),
    ("math.probability", "mathematics", "离散概率", "Discrete probability"),
    ("math.expected-value", "mathematics", "期望值", "Expected values"),
    ("math.matrix-exponentiation", "mathematics", "矩阵快速幂", "Matrix exponentiation"),
    ("math.linear-algebra", "mathematics", "线性代数基础", "Linear algebra fundamentals"),
    ("math.gaussian-elimination", "mathematics", "高斯消元", "Gaussian elimination"),
    ("math.game-theory", "mathematics", "组合博弈", "Combinatorial game theory"),
    # Computational geometry
    ("geometry.points-vectors", "geometry", "点与向量", "Points and vectors"),
    ("geometry.cross-product", "geometry", "叉积", "Cross products"),
    ("geometry.dot-product", "geometry", "点积", "Dot products"),
    ("geometry.orientation", "geometry", "方向判定", "Orientation tests"),
    ("geometry.segment-intersection", "geometry", "线段相交", "Segment intersection"),
    ("geometry.point-in-polygon", "geometry", "点在多边形内", "Point in polygon"),
    ("geometry.polygon-area", "geometry", "多边形面积", "Polygon area"),
    ("geometry.convex-hull", "geometry", "凸包", "Convex hull"),
    ("geometry.rotating-calipers", "geometry", "旋转卡壳", "Rotating calipers"),
    ("geometry.closest-pair", "geometry", "最近点对", "Closest pair of points"),
    ("geometry.line-sweep", "geometry", "扫描线", "Sweep-line geometry"),
    ("geometry.circle", "geometry", "圆几何", "Circle geometry"),
    # Advanced data structures
    ("advanced.dsu", "advanced-structures", "并查集", "Disjoint-set union"),
    ("advanced.weighted-dsu", "advanced-structures", "带权并查集", "Weighted disjoint-set union"),
    ("advanced.fenwick", "advanced-structures", "树状数组", "Fenwick trees"),
    ("advanced.segment-tree", "advanced-structures", "线段树", "Segment trees"),
    ("advanced.lazy-segment-tree", "advanced-structures", "懒标记线段树", "Lazy segment trees"),
    (
        "advanced.persistent-segment-tree",
        "advanced-structures",
        "可持久化线段树",
        "Persistent segment trees",
    ),
    (
        "advanced.dynamic-segment-tree",
        "advanced-structures",
        "动态开点线段树",
        "Dynamic segment trees",
    ),
    ("advanced.treap", "advanced-structures", "Treap", "Treaps"),
    ("advanced.splay", "advanced-structures", "伸展树", "Splay trees"),
    ("advanced.skip-list", "advanced-structures", "跳表", "Skip lists"),
    ("advanced.bloom-filter", "advanced-structures", "布隆过滤器", "Bloom filters"),
    ("advanced.mo-algorithm", "advanced-structures", "莫队算法", "Mo's algorithm"),
    ("advanced.sqrt-decomposition", "advanced-structures", "分块", "Square-root decomposition"),
    ("advanced.ordered-disjoint-tree", "advanced-structures", "珂朵莉树", "Ordered disjoint tree"),
    # Complexity and engineering
    ("complexity.time", "complexity-engineering", "时间复杂度", "Time complexity"),
    ("complexity.space", "complexity-engineering", "空间复杂度", "Space complexity"),
    ("complexity.amortized", "complexity-engineering", "均摊分析", "Amortized analysis"),
    (
        "complexity.recursion-tree",
        "complexity-engineering",
        "递归树分析",
        "Recursion-tree analysis",
    ),
    ("complexity.master-theorem", "complexity-engineering", "主定理", "Master theorem"),
    ("complexity.lower-bounds", "complexity-engineering", "复杂度下界", "Complexity lower bounds"),
    ("engineering.boundaries", "complexity-engineering", "边界条件设计", "Boundary-case design"),
    ("engineering.overflow", "complexity-engineering", "整数溢出", "Integer overflow"),
    ("engineering.floating-error", "complexity-engineering", "浮点误差", "Floating-point error"),
    ("engineering.testing", "complexity-engineering", "测试用例设计", "Test-case design"),
    ("engineering.debugging", "complexity-engineering", "程序调试", "Program debugging"),
    ("engineering.profiling", "complexity-engineering", "性能分析", "Performance profiling"),
    ("engineering.memory", "complexity-engineering", "内存管理", "Memory management"),
    ("engineering.concurrency", "complexity-engineering", "并发模型", "Concurrency models"),
    ("engineering.race-condition", "complexity-engineering", "竞态条件", "Race conditions"),
    ("engineering.deadlock", "complexity-engineering", "死锁分析", "Deadlock analysis"),
    (
        "engineering.determinism",
        "complexity-engineering",
        "确定性与可复现性",
        "Determinism and reproducibility",
    ),
    ("engineering.input-validation", "complexity-engineering", "输入校验", "Input validation"),
    (
        "engineering.secure-coding",
        "complexity-engineering",
        "安全编码基础",
        "Secure coding fundamentals",
    ),
    ("engineering.api-contracts", "complexity-engineering", "接口契约", "API contracts"),
)

KNOWLEDGE_POINTS = tuple(
    {
        "id": point_id,
        "category_id": category_id,
        "zh-CN": zh,
        "en": en,
        "aliases": (),
    }
    for point_id, category_id, zh, en in _ENTRIES
)

_BY_ID = {item["id"]: item for item in KNOWLEDGE_POINTS}


def knowledge_point(point_id: str):
    """Return one registry entry or ``None`` without accepting display labels."""

    return _BY_ID.get(str(point_id))


def resolve_knowledge_points(point_ids):
    """Validate, de-duplicate and preserve the caller's stable selection order."""

    if not isinstance(point_ids, list) or len(point_ids) > 50:
        raise ValueError("knowledge point ids must be a list of at most 50 items")
    result = []
    seen = set()
    for raw in point_ids:
        if not isinstance(raw, str) or raw not in _BY_ID:
            raise ValueError("unknown knowledge point id")
        if raw not in seen:
            seen.add(raw)
            result.append(_BY_ID[raw])
    return result
